server :
  port : 3900

spring :
  config :
    name : ltl-service-config

  cloud :
    config :
      server :
        git :
          uri : https://github.com/pablinchapin/spring-boot-micro-eco-tlal-config.git
          clone-on-start : true

management :
  endpoints :
    web :
      exposure :
        incluide : "*"